logging:
  level:
    root: DEBUG
server:
  port: 8080
spring:
  data:
    mongodb:
      #      username: root
      #      password: root
      database: test
      port: 27017
      host: localhost