eureka:
  instance:
    hostname: ${HOST_NAME:localhost}
    preferIpAddress: true
logging:
  level:
    root: ERROR
    uk:
      co:
        jamesmcguigan:
          forecaster:
            stock:
              acquisition: INFO
management:
  server:
    port: 9000
server:
  port: 8080
spring:
  data:
    mongodb:
      #      username: root
      #      password: root
      database: test
      port: 27017
      host: host.docker.internal