apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: discovery-service
    jib:
      project: discovery-service
  - image: stock-service
    jib:
      project: stock-service
  - image: notification-service
    jib:
      project: notification-service
  - image: data-acquisition-service
    jib:
      project: data-acquisition-service
  - image: ui
    jib:
      project: ui
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
    - ./kubernetes-manifests/**/**.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: dockerfile
  build:
    artifacts:
    - image: stock-service
      context: stock-service
    - image: data-acquisition-service
      context: data-acquisition-service
    - image: notification-service
      context: notification-service
    - image: ui
      context: ui
