apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: gateway-service
    jib:
      project: gateway-service
  - image: discovery-service
    jib:
      project: discovery-service
  - image: stock-service
    jib:
      project: stock-service
  - image: notification-service
    jib:
      project: notification-service
  - image: intra-day-service
    jib:
      project: intra-day-service
  - image: historical-price-service
    jib:
      project: historical-price-service
  - image: trend-service
    jib:
      project: trend-service
  - image: pattern-identification-service
    jib:
      project: pattern-identification-service
  - image: ui
    jib:
      project: ui
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
    - ./kubernetes-manifests/**/**.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: dockerfile
  build:
    artifacts:
    - image: gateway-service
      context: gateway-service
    - image: discovery-service
      context: discovery-service
    - image: stock-service
      context: stock-service
    - image: intra-day-service
      context: intra-day-service
    - image: historical-price-service
      context: historical-price-service
    - image: notification-service
      context: notification-service
    - image: trend-service
      context: trend-service
    - image: pattern-identification-service
      context: pattern-identification-service
    - image: ui
      context: ui
