apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: forecaster
  labels:
    app: ui
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
      tier: frontend
  template:
    metadata:
      labels:
        app: ui
        tier: frontend
    spec:
      containers:
      - name: ui
        image: ui
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: GUESTBOOK_API_ADDR
          value: forecaster-data-acquisition:8080
