apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecaster-frontend
  labels:
    app: forecaster
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecaster
      tier: frontend
  template:
    metadata:
      labels:
        app: forecaster
        tier: frontend
    spec:
      containers:
      - name: ui
        image: forecaster-ui
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_API_ADDR
          value: forecaster-data-acquisition:8080
