apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: stock-update
spec:
  schedule: "*/4 * * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: stock-update
              image: buildpack-deps:curl
              args:
                - /bin/sh
                - -ec
                - curl -X PUT --header "ContentType:Application/json" "http://${FORECASTER_STOCK_SERVICE}/api/stocks/"
              env:
                - name: FORECASTER_STOCK_SERVICE
                  value: forecaster-stock:8088
          restartPolicy: Never
