apiVersion: v1
kind: Service
metadata:
  name: forecaster-data-acquisition
  labels:
    app: notification-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: notification-service
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
