apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: forecaster
  labels:
    app: notification-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      tier: backend
  template:
    metadata:
      labels:
        app: notification-service
        tier: backend
    spec:
      containers:
      - name: notification-service
        image: notification-service
        ports:
        - name: http-server
          containerPort: 8080

