eureka:
  instance:
    hostname: ${HOST_NAME:localhost}
    preferIpAddress: true
logging:
  level:
    root: ERROR
    uk:
      co:
        jamesmcguigan:
          forecaster:
            ui: INFO
management:
  server:
    port: 9000
server:
  port: 8080
