apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: trends-update
  namespace: forecaster
spec:
  schedule: "*/4 * * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: trends-update
              image: buildpack-deps:curl
              args:
                - /bin/sh
                - -ec
                - curl -X POST --header "ContentType:Application/json" "http://${FORECASTER_DATA_ACQUISITION_SERVICE}/api/data-acquisition/trends/"
              env:
                - name: FORECASTER_DATA_ACQUISITION_SERVICE
                  value: data-acquisition-service
          restartPolicy: Never