apiVersion: v1
kind: Service
metadata:
  name: intra-day-service
  namespace: forecaster
  labels:
    app: intra-day-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: intra-day-service
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
